### ISSUE TITLE
Changing entry disabled hot reloading

### ISSUE THREAD

**Issue by padcom** [upash/poi#463]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Setting entry to anything other than `main` disables hot reloading of changes

**If the current behavior is a bug, please provide the steps to reproduce.**
```
module.exports = {
  entry: {
    index: './index',
  },
}
```

**What is the expected behavior?**
Sometimes it is necessary to adjust the generated file name so that it is not `main.js` and `main.css` - especially if adding POI as build step to existing projects.
I expect that changing entry name doesn't disable hot reloading. This should also hold true for multiple entry points.

**Please mention other relevant information such as the browser version, Node.js version, Poi version and Operating System.**

POI: 10.2.9

**Comment by padcom** [comment]
If that is too much of a problem (which it definitely shouldn't be) at the very least mention that in the documentation. There is no mentioning of it in the docs and previous version (9.x) didn't have that _feature_.

**Comment by egoist** [comment]
you can use [filename](https://poi.js.org/options.html#filename) to change the filename.

you can also use [hotEntry](https://poi.js.org/options.html#hotentry) option to make specific entry hot reloadable.

**Comment by egoist** [comment]
you can use [filename](https://poi.js.org/options.html#filename) to change the filename.

you can also use [hotEntry](https://poi.js.org/options.html#hotentry) option to make specific entry hot reloadable.

**Comment by padcom** [comment]
Thanks
